### ISSUE TITLE
Should JDK Dynamic proxy also be handled?

### ISSUE THREAD

**Issue by tongc** [spring-projects/spring-framework-issues#106]
So with
public class Controller implements ApplicationListener<ApplicationEvent>
Spring no longer proxy Controller using CGLIB but instead using JDK Dynamic Proxy.

**Comment by snicoll** [comment]
You're creating the issue in the wrong repository.

Issue should be raised in [the Spring Framework issue tracker](https://jira.spring.io/browse/SPR). It looks like you're asking a question. Please use StackOverflow for that.
