### ISSUE TITLE
org.springframework.web.multipart.support.MultipartResolutionDelegate has a bug

### ISSUE THREAD

**Issue by mycoin** [spring-projects/spring-framework-issues#137]
RT 
spring 5.3.0

This is my controller method
```
@RequestMapping(method = RequestMethod.GET)
public void env(ModelAndView mv) throws Exception {
     System.out.println(mv);
}
```

and

```
<mvc:annotation-driven />
```

But method `isMultipartArgument`  called from 
org.springframework.web.method.annotation.RequestParamMethodArgumentResolver.supportsParameter(MethodParameter)

```
public boolean supportsParameter(MethodParameter parameter) {
    if (parameter.hasParameterAnnotation(RequestParam.class)) {
        if (Map.class.isAssignableFrom(parameter.nestedIfOptional().getNestedParameterType())) {
            String paramName = parameter.getParameterAnnotation(RequestParam.class).name();
            return StringUtils.hasText(paramName);
        }
        else {
            return true;
        }
    }
    else {
        if (parameter.hasParameterAnnotation(RequestPart.class)) {
            return false;
        }
        parameter = parameter.nestedIfOptional();
        if (MultipartResolutionDelegate.isMultipartArgument(parameter)) {
            // return true, whatever parameter is!!
            return true;
        }
        else if (this.useDefaultResolution) {
            return BeanUtils.isSimpleProperty(parameter.getNestedParameterType());
        }
        else {
            return false;
        }
    }
}
```

then I got a null ModelAndView~

**Comment by snicoll** [comment]
This is not the tracker of the Spring Framework, please [have a look to the readme](https://github.com/spring-projects/spring-framework-issues/blob/master/README.md). Spring Framework issues have to be reported at [jira.spring.io](https://jira.spring.io/browse/SPR)

**Comment by mycoin** [comment]
I found MultipartResolutionDelegate.java

method 
```
private static boolean isPartCollection(MethodParameter methodParam) {
    return (servletPartClass == getCollectionParameterType(methodParam));
}
```

field servletPartClass is null, maybe 
``` java
private static boolean isPartCollection(MethodParameter methodParam) {
    return (servletPartClass == getCollectionParameterType(methodParam));
}
```
@jhoeller 

field servletPartClass is null null == null ,so always return true.

**Comment by jhoeller** [comment]
I assume you're running in a Servlet 2.5 environment there? Then this looks a lot like https://jira.spring.io/browse/SPR-14358, which has been fixed in the recently released 4.3.1 already.

**Comment by mycoin** [comment]
Ok  thanks a lot ~ 👍

**Comment by jhoeller** [comment]
Out of curiosity, which server are you running on there: WebSphere 7? Tomcat 6? Google App Engine?

**Comment by mycoin** [comment]
@jhoeller The project is running under jetty-6.1.26, and JDK version is 1.6

Whatever, spring-5.3.1 works well ~ Thanks
