### ISSUE TITLE
I found a proxy bug,maybe caused by spring or jdk

### ISSUE THREAD

**Issue by devpage** [spring-projects/spring-framework-issues#168]
code path : https://github.com/devpage/spring4-mvc-gradle-async-http-proxy

access http://localhost:8080/spring4/query/async/error  then will trigger a TimeoutException,
look terminal logs at '^^^^^^^^simple^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^' line,
compare '^^^^^^^^simple^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^' end content with asyncHttpApiExecutorProxy.callAsyncApiByBody 2th param Class Type ,
you will found it

**Comment by snicoll** [comment]
@devpage this project is used to report repro sample for issues raised on [our issue tracker](https://jira.spring.io/browse/SPR). Please ask that question on stackoverflow.
