### ISSUE TITLE
Spring 5 CommonsPool2TargetSource Returned object not currently part of this pool

### ISSUE THREAD

**Issue by gauravtyagi77** [spring-projects/spring-framework-issues#181]
Hi,

I am facing java.lang.IllegalStateException: Returned object not currently part of this pool while calling releaseTarget on autowired CommonsPool2TargetSource while it was working earlier before upgrading to spring 5 and using CommonsPool2TargetSource in place of CommonsPoolTargetSource.

Please assist.

Regards,
Gaurav

**Comment by shakunahuja** [comment]
Same problem for me as well

**Comment by snicoll** [comment]
This issue tracker is not meant to raise Spring Framework's issue. The issue tracker is [here](https://jira.spring.io/browse/SPR). Before raisin an issue there, consider collecting more details and a complete stacktrace. A sample would be idea.
