### ISSUE TITLE
BeanCreationException logging as warn and not error

### ISSUE THREAD

**Issue by pminearo** [spring-projects/spring-framework-issues#93]
We just upgraded to Spring 4.1.4 and noticed an problem when creating our ApplicationContext:

2015-02-25 03:00:00,119 WARN  [o.s.c.s.ClassPathXmlApplicationContext] [quartzScheduler$child#0_Worker-1]: Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'beanName': Cannot resolve reference to bean 'beanName' while setting bean property 'tasklet'; nested exception is org.spr
ingframework.beans.factory.BeanCreationException: Error creating bean with name 'beanName' defined in class path resource [spring-config.xml]: Initialization of bean failed; nested exception is org.springframework.
beans.TypeMismatchException: Failed to convert property value of type 'java.lang.String' to required type 'boolean' for property 'disabled'; nested exception is java.lang.IllegalArgumentException: Invalid boolean value [${disabledField}]

Yes, I know the XmlBeanFactory is deprecated and we have remedied this problem. But what we don't understand is why this message logged as a WARN and not an ERROR? Shouldn't any BeanCreationException be logged as an ERROR to say the ApplicationContext is not being created as intended?

**Comment by snicoll** [comment]
Hello,

This project is used to contribute sample projects for spring framework issues, this is not the Spring Framework issue tracker. 

I don't see any reference to `XmlBeanFactory` in here. Please create an issue at jira.spring.io/browse/SPR and provide more details such as your previous version and the steps to reproduce the issue. Or a sample project you could contribute here! Thanks.

**Comment by jhoeller** [comment]
As for the 'warn' level there: Note that we are propagating that exception to whoever triggered the refresh, so the exception should eventually show up as an error higher up. Is it being swallowed in your specific bootstrap arrangement?

We're only logging it at 'warn' level primarily for the reason that it's really up to the caller to decide whether a failed refresh attempt is an actual error or can be remedied somehow, possibly in a dynamic environment with many contexts.
